on:
  push:
    branches:
          - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Run tests
        run: mvn test
      - name: Generate tag
        run: echo "tag=$(date +'%Y%m%d.%H%M%S')" >> $GITHUB_OUTPUT
        id: timestamp
      - name: Generate Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/items:${{steps.timestamp.outputs.tag}} .
            docker tag ${{ secrets.DOCKERHUB_USERNAME }}/items:${{steps.timestamp.outputs.tag}} ${{ secrets.DOCKERHUB_USERNAME }}/items:${{github.sha}}
      - name: Login to DockerHub
        run: docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}" 
      - name: Push image to DockerHub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/items:dev-${{steps.timestamp.outputs.tag}}


